version: 0.2

env:
  variables:
     ACCOUNT_ID_LIST: ""
     CFN_NAME: ""   # Make sure the template name here matches the template name under cloudformation folder!

phases:

  pre_build:
    commands:
      - echo Entered the pre_build phase
      - echo "CFN will be deployed..."


  build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      
      - git clone https://github.com/mjs6898/demo-1.git
      - python cf.py template.yaml


  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`



